### ISSUE TITLE
Monsters that wandered upward ignore iPad mode

### ISSUE THREAD

**Issue by crazymachinefan** [pizzajacob/Toads-and-Orcs#10]
They don’t use non-iPad mode either.

**Comment by pizzajacob** [comment]
I'm not exactly sure what this means. Is the text not displaying properly? Is the monster itself not working properly?

**Comment by crazymachinefan** [comment]
The gaps between groups of text (merchants, magenta circles, monsters, pits, etc) is brought down to 0 from the skill point screen before the fight to the final fight screen

ie:
Merchant


Skillpoint


Pit


Skillpoint
Fight
Fight
Fight


Skillpoint


This forces the fight to take place behind the iOS keyboard.

**Comment by pizzajacob** [comment]
Thanks for the response, I'll try to get this fixed in v1.5

**Comment by pizzajacob** [comment]
Should be fixed in v1.5, reopen if not fixed
